#define SDL2RKEYBOARD
#include "sdl2r.h"
#include "sdl2r_window.h"
#include "sdl2r_keyboard.h"

VALUE sdl2r_enum_ScancodeEnum;
VALUE sdl2r_enum_KeycodeEnum;
VALUE sdl2r_enum_KeymodEnum;

static VALUE sdl2r_get_key_name(VALUE klass, VALUE vkeycode)
{
    const char *result;

    result = SDL_GetKeyName((SDL_Keycode)NUM2INT(vkeycode));
    return SDL2R_TO_UTF8_STRING(result);
}


static VALUE sdl2r_get_key_from_name(VALUE klass, VALUE vkeyname)
{
    SDL_Keycode result;

    result = SDL_GetKeyFromName(SDL2R_TO_UTF8_PTR(vkeyname));
    return INT2NUM(result);
}


static VALUE sdl2r_get_key_from_scancode(VALUE klass, VALUE vscancode)
{
    SDL_Keycode result;

    result = SDL_GetKeyFromScancode(NUM2INT(vscancode));
    return INT2NUM(result);
}


static VALUE sdl2r_get_keyboard_focus(VALUE klass)
{
    SDL_Window *w;

    w = SDL_GetKeyboardFocus();
    return sdl2r_window_sdl_to_ruby(w);
}


static VALUE sdl2r_get_scancode_from_key(VALUE klass, VALUE vkeycode)
{
    SDL_Scancode result;

    result = SDL_GetScancodeFromKey(NUM2INT(vkeycode));
    return INT2NUM(result);
}


static VALUE sdl2r_get_scancode_from_name(VALUE klass, VALUE vkeyname)
{
    SDL_Scancode result;

    result = SDL_GetScancodeFromName(SDL2R_TO_UTF8_PTR(vkeyname));
    return INT2NUM(result);
}


static VALUE sdl2r_get_scancode_name(VALUE klass, VALUE vscancode)
{
    const char *result;

    result = SDL_GetScancodeName((SDL_Scancode)NUM2INT(vscancode));
    return SDL2R_TO_UTF8_STRING(result);
}


static VALUE sdl2r_start_text_input(VALUE klass)
{
    SDL_StartTextInput();
    return Qnil;
}


static VALUE sdl2r_stop_text_input(VALUE klass)
{
    SDL_StopTextInput();
    return Qnil;
}


static VALUE sdl2r_set_text_input_rect(VALUE klass, VALUE vrect)
{
    SDL_Rect rect;
    SDL_Rect *pr=0;

    if (vrect != Qnil) {
        SDL2R_SET_RECT(rect, vrect);
        pr = &rect;
    }

    SDL_SetTextInputRect(pr);
    return Qnil;
}


static VALUE sdl2r_get_mod_state(VALUE klass)
{
    SDL_Keymod result;

    result = SDL_GetModState();
    return INT2NUM(result);
}


static VALUE sdl2r_set_mod_state(VALUE klass, VALUE vkeymod)
{
    SDL_SetModState(NUM2INT(vkeymod));
    return Qnil;
}


static VALUE sdl2r_get_keyboard_state(VALUE klass)
{
    int numkeys, i;
    const Uint8 *c = SDL_GetKeyboardState(&numkeys);
    VALUE vresult = rb_ary_new();

    if (numkeys) {
        for (i = 0; i < numkeys; i++) {
            rb_ary_push(vresult, UINT2NUM(c[i]));
        }
    }
    return vresult;
}


static VALUE sdl2r_has_screen_keyboard_support(VALUE klass)
{
    SDL_bool result;

    result = SDL_HasScreenKeyboardSupport();
    return SDL2R_TO_BOOL(result);
}


static VALUE sdl2r_is_screen_keyboard_shown(VALUE klass, VALUE vwindow)
{
    SDL_bool result;
    struct SDL2RWindow *win = SDL2R_GET_WINDOW_STRUCT(vwindow);

    result = SDL_IsScreenKeyboardShown(win->window);
    return SDL2R_TO_BOOL(result);
}


static VALUE sdl2r_is_text_input_active(VALUE klass)
{
    SDL_bool result;

    result = SDL_IsTextInputActive();
    return SDL2R_TO_BOOL(result);
}


void Init_sdl2r_keyboard(void)
{
    // SDL module methods
    SDL2R_DEFINE_SINGLETON_METHOD(get_key_name, 1);
    SDL2R_DEFINE_SINGLETON_METHOD(get_key_from_name, 1);
    SDL2R_DEFINE_SINGLETON_METHOD(get_key_from_scancode, 1);
    SDL2R_DEFINE_SINGLETON_METHOD(get_keyboard_focus, 0);
    SDL2R_DEFINE_SINGLETON_METHOD(get_scancode_name, 1);
    SDL2R_DEFINE_SINGLETON_METHOD(get_scancode_from_key, 1);
    SDL2R_DEFINE_SINGLETON_METHOD(get_scancode_from_name, 1);
    SDL2R_DEFINE_SINGLETON_METHOD(start_text_input, 0);
    SDL2R_DEFINE_SINGLETON_METHOD(stop_text_input, 0);
    SDL2R_DEFINE_SINGLETON_METHOD(set_text_input_rect, 1);
    SDL2R_DEFINE_SINGLETON_METHOD(get_mod_state, 0);
    SDL2R_DEFINE_SINGLETON_METHOD(set_mod_state, 1);
    SDL2R_DEFINE_SINGLETON_METHOD(get_keyboard_state, 0);
    SDL2R_DEFINE_SINGLETON_METHOD(has_screen_keyboard_support, 0);
    SDL2R_DEFINE_SINGLETON_METHOD(is_screen_keyboard_shown, 1);
    SDL2R_DEFINE_SINGLETON_METHOD(is_text_input_active, 0);

    // Enum
    SDL2R_DEFINE_ENUM(ScancodeEnum);
    SDL2R_DEFINE_ENUM_VALUE(ScancodeEnum, SCANCODE_UNKNOWN);
    SDL2R_DEFINE_ENUM_VALUE(ScancodeEnum, SCANCODE_A);
    SDL2R_DEFINE_ENUM_VALUE(ScancodeEnum, SCANCODE_B);
    SDL2R_DEFINE_ENUM_VALUE(ScancodeEnum, SCANCODE_C);
    SDL2R_DEFINE_ENUM_VALUE(ScancodeEnum, SCANCODE_D);
    SDL2R_DEFINE_ENUM_VALUE(ScancodeEnum, SCANCODE_E);
    SDL2R_DEFINE_ENUM_VALUE(ScancodeEnum, SCANCODE_F);
    SDL2R_DEFINE_ENUM_VALUE(ScancodeEnum, SCANCODE_G);
    SDL2R_DEFINE_ENUM_VALUE(ScancodeEnum, SCANCODE_H);
    SDL2R_DEFINE_ENUM_VALUE(ScancodeEnum, SCANCODE_I);
    SDL2R_DEFINE_ENUM_VALUE(ScancodeEnum, SCANCODE_J);
    SDL2R_DEFINE_ENUM_VALUE(ScancodeEnum, SCANCODE_K);
    SDL2R_DEFINE_ENUM_VALUE(ScancodeEnum, SCANCODE_L);
    SDL2R_DEFINE_ENUM_VALUE(ScancodeEnum, SCANCODE_M);
    SDL2R_DEFINE_ENUM_VALUE(ScancodeEnum, SCANCODE_N);
    SDL2R_DEFINE_ENUM_VALUE(ScancodeEnum, SCANCODE_O);
    SDL2R_DEFINE_ENUM_VALUE(ScancodeEnum, SCANCODE_P);
    SDL2R_DEFINE_ENUM_VALUE(ScancodeEnum, SCANCODE_Q);
    SDL2R_DEFINE_ENUM_VALUE(ScancodeEnum, SCANCODE_R);
    SDL2R_DEFINE_ENUM_VALUE(ScancodeEnum, SCANCODE_S);
    SDL2R_DEFINE_ENUM_VALUE(ScancodeEnum, SCANCODE_T);
    SDL2R_DEFINE_ENUM_VALUE(ScancodeEnum, SCANCODE_U);
    SDL2R_DEFINE_ENUM_VALUE(ScancodeEnum, SCANCODE_V);
    SDL2R_DEFINE_ENUM_VALUE(ScancodeEnum, SCANCODE_W);
    SDL2R_DEFINE_ENUM_VALUE(ScancodeEnum, SCANCODE_X);
    SDL2R_DEFINE_ENUM_VALUE(ScancodeEnum, SCANCODE_Y);
    SDL2R_DEFINE_ENUM_VALUE(ScancodeEnum, SCANCODE_Z);
    SDL2R_DEFINE_ENUM_VALUE(ScancodeEnum, SCANCODE_1);
    SDL2R_DEFINE_ENUM_VALUE(ScancodeEnum, SCANCODE_2);
    SDL2R_DEFINE_ENUM_VALUE(ScancodeEnum, SCANCODE_3);
    SDL2R_DEFINE_ENUM_VALUE(ScancodeEnum, SCANCODE_4);
    SDL2R_DEFINE_ENUM_VALUE(ScancodeEnum, SCANCODE_5);
    SDL2R_DEFINE_ENUM_VALUE(ScancodeEnum, SCANCODE_6);
    SDL2R_DEFINE_ENUM_VALUE(ScancodeEnum, SCANCODE_7);
    SDL2R_DEFINE_ENUM_VALUE(ScancodeEnum, SCANCODE_8);
    SDL2R_DEFINE_ENUM_VALUE(ScancodeEnum, SCANCODE_9);
    SDL2R_DEFINE_ENUM_VALUE(ScancodeEnum, SCANCODE_0);
    SDL2R_DEFINE_ENUM_VALUE(ScancodeEnum, SCANCODE_RETURN);
    SDL2R_DEFINE_ENUM_VALUE(ScancodeEnum, SCANCODE_ESCAPE);
    SDL2R_DEFINE_ENUM_VALUE(ScancodeEnum, SCANCODE_BACKSPACE);
    SDL2R_DEFINE_ENUM_VALUE(ScancodeEnum, SCANCODE_TAB);
    SDL2R_DEFINE_ENUM_VALUE(ScancodeEnum, SCANCODE_SPACE);
    SDL2R_DEFINE_ENUM_VALUE(ScancodeEnum, SCANCODE_MINUS);
    SDL2R_DEFINE_ENUM_VALUE(ScancodeEnum, SCANCODE_EQUALS);
    SDL2R_DEFINE_ENUM_VALUE(ScancodeEnum, SCANCODE_LEFTBRACKET);
    SDL2R_DEFINE_ENUM_VALUE(ScancodeEnum, SCANCODE_RIGHTBRACKET);
    SDL2R_DEFINE_ENUM_VALUE(ScancodeEnum, SCANCODE_BACKSLASH);
    SDL2R_DEFINE_ENUM_VALUE(ScancodeEnum, SCANCODE_NONUSHASH);
    SDL2R_DEFINE_ENUM_VALUE(ScancodeEnum, SCANCODE_SEMICOLON);
    SDL2R_DEFINE_ENUM_VALUE(ScancodeEnum, SCANCODE_APOSTROPHE);
    SDL2R_DEFINE_ENUM_VALUE(ScancodeEnum, SCANCODE_GRAVE);
    SDL2R_DEFINE_ENUM_VALUE(ScancodeEnum, SCANCODE_COMMA);
    SDL2R_DEFINE_ENUM_VALUE(ScancodeEnum, SCANCODE_PERIOD);
    SDL2R_DEFINE_ENUM_VALUE(ScancodeEnum, SCANCODE_SLASH);
    SDL2R_DEFINE_ENUM_VALUE(ScancodeEnum, SCANCODE_CAPSLOCK);
    SDL2R_DEFINE_ENUM_VALUE(ScancodeEnum, SCANCODE_F1);
    SDL2R_DEFINE_ENUM_VALUE(ScancodeEnum, SCANCODE_F2);
    SDL2R_DEFINE_ENUM_VALUE(ScancodeEnum, SCANCODE_F3);
    SDL2R_DEFINE_ENUM_VALUE(ScancodeEnum, SCANCODE_F4);
    SDL2R_DEFINE_ENUM_VALUE(ScancodeEnum, SCANCODE_F5);
    SDL2R_DEFINE_ENUM_VALUE(ScancodeEnum, SCANCODE_F6);
    SDL2R_DEFINE_ENUM_VALUE(ScancodeEnum, SCANCODE_F7);
    SDL2R_DEFINE_ENUM_VALUE(ScancodeEnum, SCANCODE_F8);
    SDL2R_DEFINE_ENUM_VALUE(ScancodeEnum, SCANCODE_F9);
    SDL2R_DEFINE_ENUM_VALUE(ScancodeEnum, SCANCODE_F10);
    SDL2R_DEFINE_ENUM_VALUE(ScancodeEnum, SCANCODE_F11);
    SDL2R_DEFINE_ENUM_VALUE(ScancodeEnum, SCANCODE_F12);
    SDL2R_DEFINE_ENUM_VALUE(ScancodeEnum, SCANCODE_PRINTSCREEN);
    SDL2R_DEFINE_ENUM_VALUE(ScancodeEnum, SCANCODE_SCROLLLOCK);
    SDL2R_DEFINE_ENUM_VALUE(ScancodeEnum, SCANCODE_PAUSE);
    SDL2R_DEFINE_ENUM_VALUE(ScancodeEnum, SCANCODE_INSERT);
    SDL2R_DEFINE_ENUM_VALUE(ScancodeEnum, SCANCODE_HOME);
    SDL2R_DEFINE_ENUM_VALUE(ScancodeEnum, SCANCODE_PAGEUP);
    SDL2R_DEFINE_ENUM_VALUE(ScancodeEnum, SCANCODE_DELETE);
    SDL2R_DEFINE_ENUM_VALUE(ScancodeEnum, SCANCODE_END);
    SDL2R_DEFINE_ENUM_VALUE(ScancodeEnum, SCANCODE_PAGEDOWN);
    SDL2R_DEFINE_ENUM_VALUE(ScancodeEnum, SCANCODE_RIGHT);
    SDL2R_DEFINE_ENUM_VALUE(ScancodeEnum, SCANCODE_LEFT);
    SDL2R_DEFINE_ENUM_VALUE(ScancodeEnum, SCANCODE_DOWN);
    SDL2R_DEFINE_ENUM_VALUE(ScancodeEnum, SCANCODE_UP);
    SDL2R_DEFINE_ENUM_VALUE(ScancodeEnum, SCANCODE_NUMLOCKCLEAR);
    SDL2R_DEFINE_ENUM_VALUE(ScancodeEnum, SCANCODE_KP_DIVIDE);
    SDL2R_DEFINE_ENUM_VALUE(ScancodeEnum, SCANCODE_KP_MULTIPLY);
    SDL2R_DEFINE_ENUM_VALUE(ScancodeEnum, SCANCODE_KP_MINUS);
    SDL2R_DEFINE_ENUM_VALUE(ScancodeEnum, SCANCODE_KP_PLUS);
    SDL2R_DEFINE_ENUM_VALUE(ScancodeEnum, SCANCODE_KP_ENTER);
    SDL2R_DEFINE_ENUM_VALUE(ScancodeEnum, SCANCODE_KP_1);
    SDL2R_DEFINE_ENUM_VALUE(ScancodeEnum, SCANCODE_KP_2);
    SDL2R_DEFINE_ENUM_VALUE(ScancodeEnum, SCANCODE_KP_3);
    SDL2R_DEFINE_ENUM_VALUE(ScancodeEnum, SCANCODE_KP_4);
    SDL2R_DEFINE_ENUM_VALUE(ScancodeEnum, SCANCODE_KP_5);
    SDL2R_DEFINE_ENUM_VALUE(ScancodeEnum, SCANCODE_KP_6);
    SDL2R_DEFINE_ENUM_VALUE(ScancodeEnum, SCANCODE_KP_7);
    SDL2R_DEFINE_ENUM_VALUE(ScancodeEnum, SCANCODE_KP_8);
    SDL2R_DEFINE_ENUM_VALUE(ScancodeEnum, SCANCODE_KP_9);
    SDL2R_DEFINE_ENUM_VALUE(ScancodeEnum, SCANCODE_KP_0);
    SDL2R_DEFINE_ENUM_VALUE(ScancodeEnum, SCANCODE_KP_PERIOD);
    SDL2R_DEFINE_ENUM_VALUE(ScancodeEnum, SCANCODE_NONUSBACKSLASH);
    SDL2R_DEFINE_ENUM_VALUE(ScancodeEnum, SCANCODE_APPLICATION);
    SDL2R_DEFINE_ENUM_VALUE(ScancodeEnum, SCANCODE_POWER);
    SDL2R_DEFINE_ENUM_VALUE(ScancodeEnum, SCANCODE_KP_EQUALS);
    SDL2R_DEFINE_ENUM_VALUE(ScancodeEnum, SCANCODE_F13);
    SDL2R_DEFINE_ENUM_VALUE(ScancodeEnum, SCANCODE_F14);
    SDL2R_DEFINE_ENUM_VALUE(ScancodeEnum, SCANCODE_F15);
    SDL2R_DEFINE_ENUM_VALUE(ScancodeEnum, SCANCODE_F16);
    SDL2R_DEFINE_ENUM_VALUE(ScancodeEnum, SCANCODE_F17);
    SDL2R_DEFINE_ENUM_VALUE(ScancodeEnum, SCANCODE_F18);
    SDL2R_DEFINE_ENUM_VALUE(ScancodeEnum, SCANCODE_F19);
    SDL2R_DEFINE_ENUM_VALUE(ScancodeEnum, SCANCODE_F20);
    SDL2R_DEFINE_ENUM_VALUE(ScancodeEnum, SCANCODE_F21);
    SDL2R_DEFINE_ENUM_VALUE(ScancodeEnum, SCANCODE_F22);
    SDL2R_DEFINE_ENUM_VALUE(ScancodeEnum, SCANCODE_F23);
    SDL2R_DEFINE_ENUM_VALUE(ScancodeEnum, SCANCODE_F24);
    SDL2R_DEFINE_ENUM_VALUE(ScancodeEnum, SCANCODE_EXECUTE);
    SDL2R_DEFINE_ENUM_VALUE(ScancodeEnum, SCANCODE_HELP);
    SDL2R_DEFINE_ENUM_VALUE(ScancodeEnum, SCANCODE_MENU);
    SDL2R_DEFINE_ENUM_VALUE(ScancodeEnum, SCANCODE_SELECT);
    SDL2R_DEFINE_ENUM_VALUE(ScancodeEnum, SCANCODE_STOP);
    SDL2R_DEFINE_ENUM_VALUE(ScancodeEnum, SCANCODE_AGAIN);
    SDL2R_DEFINE_ENUM_VALUE(ScancodeEnum, SCANCODE_UNDO);
    SDL2R_DEFINE_ENUM_VALUE(ScancodeEnum, SCANCODE_CUT);
    SDL2R_DEFINE_ENUM_VALUE(ScancodeEnum, SCANCODE_COPY);
    SDL2R_DEFINE_ENUM_VALUE(ScancodeEnum, SCANCODE_PASTE);
    SDL2R_DEFINE_ENUM_VALUE(ScancodeEnum, SCANCODE_FIND);
    SDL2R_DEFINE_ENUM_VALUE(ScancodeEnum, SCANCODE_MUTE);
    SDL2R_DEFINE_ENUM_VALUE(ScancodeEnum, SCANCODE_VOLUMEUP);
    SDL2R_DEFINE_ENUM_VALUE(ScancodeEnum, SCANCODE_VOLUMEDOWN);
    SDL2R_DEFINE_ENUM_VALUE(ScancodeEnum, SCANCODE_KP_COMMA);
    SDL2R_DEFINE_ENUM_VALUE(ScancodeEnum, SCANCODE_KP_EQUALSAS400);
    SDL2R_DEFINE_ENUM_VALUE(ScancodeEnum, SCANCODE_INTERNATIONAL1);
    SDL2R_DEFINE_ENUM_VALUE(ScancodeEnum, SCANCODE_INTERNATIONAL2);
    SDL2R_DEFINE_ENUM_VALUE(ScancodeEnum, SCANCODE_INTERNATIONAL3);
    SDL2R_DEFINE_ENUM_VALUE(ScancodeEnum, SCANCODE_INTERNATIONAL4);
    SDL2R_DEFINE_ENUM_VALUE(ScancodeEnum, SCANCODE_INTERNATIONAL5);
    SDL2R_DEFINE_ENUM_VALUE(ScancodeEnum, SCANCODE_INTERNATIONAL6);
    SDL2R_DEFINE_ENUM_VALUE(ScancodeEnum, SCANCODE_INTERNATIONAL7);
    SDL2R_DEFINE_ENUM_VALUE(ScancodeEnum, SCANCODE_INTERNATIONAL8);
    SDL2R_DEFINE_ENUM_VALUE(ScancodeEnum, SCANCODE_INTERNATIONAL9);
    SDL2R_DEFINE_ENUM_VALUE(ScancodeEnum, SCANCODE_LANG1);
    SDL2R_DEFINE_ENUM_VALUE(ScancodeEnum, SCANCODE_LANG2);
    SDL2R_DEFINE_ENUM_VALUE(ScancodeEnum, SCANCODE_LANG3);
    SDL2R_DEFINE_ENUM_VALUE(ScancodeEnum, SCANCODE_LANG4);
    SDL2R_DEFINE_ENUM_VALUE(ScancodeEnum, SCANCODE_LANG5);
    SDL2R_DEFINE_ENUM_VALUE(ScancodeEnum, SCANCODE_LANG6);
    SDL2R_DEFINE_ENUM_VALUE(ScancodeEnum, SCANCODE_LANG7);
    SDL2R_DEFINE_ENUM_VALUE(ScancodeEnum, SCANCODE_LANG8);
    SDL2R_DEFINE_ENUM_VALUE(ScancodeEnum, SCANCODE_LANG9);
    SDL2R_DEFINE_ENUM_VALUE(ScancodeEnum, SCANCODE_ALTERASE);
    SDL2R_DEFINE_ENUM_VALUE(ScancodeEnum, SCANCODE_SYSREQ);
    SDL2R_DEFINE_ENUM_VALUE(ScancodeEnum, SCANCODE_CANCEL);
    SDL2R_DEFINE_ENUM_VALUE(ScancodeEnum, SCANCODE_CLEAR);
    SDL2R_DEFINE_ENUM_VALUE(ScancodeEnum, SCANCODE_PRIOR);
    SDL2R_DEFINE_ENUM_VALUE(ScancodeEnum, SCANCODE_RETURN2);
    SDL2R_DEFINE_ENUM_VALUE(ScancodeEnum, SCANCODE_SEPARATOR);
    SDL2R_DEFINE_ENUM_VALUE(ScancodeEnum, SCANCODE_OUT);
    SDL2R_DEFINE_ENUM_VALUE(ScancodeEnum, SCANCODE_OPER);
    SDL2R_DEFINE_ENUM_VALUE(ScancodeEnum, SCANCODE_CLEARAGAIN);
    SDL2R_DEFINE_ENUM_VALUE(ScancodeEnum, SCANCODE_CRSEL);
    SDL2R_DEFINE_ENUM_VALUE(ScancodeEnum, SCANCODE_EXSEL);
    SDL2R_DEFINE_ENUM_VALUE(ScancodeEnum, SCANCODE_KP_00);
    SDL2R_DEFINE_ENUM_VALUE(ScancodeEnum, SCANCODE_KP_000);
    SDL2R_DEFINE_ENUM_VALUE(ScancodeEnum, SCANCODE_THOUSANDSSEPARATOR);
    SDL2R_DEFINE_ENUM_VALUE(ScancodeEnum, SCANCODE_DECIMALSEPARATOR);
    SDL2R_DEFINE_ENUM_VALUE(ScancodeEnum, SCANCODE_CURRENCYUNIT);
    SDL2R_DEFINE_ENUM_VALUE(ScancodeEnum, SCANCODE_CURRENCYSUBUNIT);
    SDL2R_DEFINE_ENUM_VALUE(ScancodeEnum, SCANCODE_KP_LEFTPAREN);
    SDL2R_DEFINE_ENUM_VALUE(ScancodeEnum, SCANCODE_KP_RIGHTPAREN);
    SDL2R_DEFINE_ENUM_VALUE(ScancodeEnum, SCANCODE_KP_LEFTBRACE);
    SDL2R_DEFINE_ENUM_VALUE(ScancodeEnum, SCANCODE_KP_RIGHTBRACE);
    SDL2R_DEFINE_ENUM_VALUE(ScancodeEnum, SCANCODE_KP_TAB);
    SDL2R_DEFINE_ENUM_VALUE(ScancodeEnum, SCANCODE_KP_BACKSPACE);
    SDL2R_DEFINE_ENUM_VALUE(ScancodeEnum, SCANCODE_KP_A);
    SDL2R_DEFINE_ENUM_VALUE(ScancodeEnum, SCANCODE_KP_B);
    SDL2R_DEFINE_ENUM_VALUE(ScancodeEnum, SCANCODE_KP_C);
    SDL2R_DEFINE_ENUM_VALUE(ScancodeEnum, SCANCODE_KP_D);
    SDL2R_DEFINE_ENUM_VALUE(ScancodeEnum, SCANCODE_KP_E);
    SDL2R_DEFINE_ENUM_VALUE(ScancodeEnum, SCANCODE_KP_F);
    SDL2R_DEFINE_ENUM_VALUE(ScancodeEnum, SCANCODE_KP_XOR);
    SDL2R_DEFINE_ENUM_VALUE(ScancodeEnum, SCANCODE_KP_POWER);
    SDL2R_DEFINE_ENUM_VALUE(ScancodeEnum, SCANCODE_KP_PERCENT);
    SDL2R_DEFINE_ENUM_VALUE(ScancodeEnum, SCANCODE_KP_LESS);
    SDL2R_DEFINE_ENUM_VALUE(ScancodeEnum, SCANCODE_KP_GREATER);
    SDL2R_DEFINE_ENUM_VALUE(ScancodeEnum, SCANCODE_KP_AMPERSAND);
    SDL2R_DEFINE_ENUM_VALUE(ScancodeEnum, SCANCODE_KP_DBLAMPERSAND);
    SDL2R_DEFINE_ENUM_VALUE(ScancodeEnum, SCANCODE_KP_VERTICALBAR);
    SDL2R_DEFINE_ENUM_VALUE(ScancodeEnum, SCANCODE_KP_DBLVERTICALBAR);
    SDL2R_DEFINE_ENUM_VALUE(ScancodeEnum, SCANCODE_KP_COLON);
    SDL2R_DEFINE_ENUM_VALUE(ScancodeEnum, SCANCODE_KP_HASH);
    SDL2R_DEFINE_ENUM_VALUE(ScancodeEnum, SCANCODE_KP_SPACE);
    SDL2R_DEFINE_ENUM_VALUE(ScancodeEnum, SCANCODE_KP_AT);
    SDL2R_DEFINE_ENUM_VALUE(ScancodeEnum, SCANCODE_KP_EXCLAM);
    SDL2R_DEFINE_ENUM_VALUE(ScancodeEnum, SCANCODE_KP_MEMSTORE);
    SDL2R_DEFINE_ENUM_VALUE(ScancodeEnum, SCANCODE_KP_MEMRECALL);
    SDL2R_DEFINE_ENUM_VALUE(ScancodeEnum, SCANCODE_KP_MEMCLEAR);
    SDL2R_DEFINE_ENUM_VALUE(ScancodeEnum, SCANCODE_KP_MEMADD);
    SDL2R_DEFINE_ENUM_VALUE(ScancodeEnum, SCANCODE_KP_MEMSUBTRACT);
    SDL2R_DEFINE_ENUM_VALUE(ScancodeEnum, SCANCODE_KP_MEMMULTIPLY);
    SDL2R_DEFINE_ENUM_VALUE(ScancodeEnum, SCANCODE_KP_MEMDIVIDE);
    SDL2R_DEFINE_ENUM_VALUE(ScancodeEnum, SCANCODE_KP_PLUSMINUS);
    SDL2R_DEFINE_ENUM_VALUE(ScancodeEnum, SCANCODE_KP_CLEAR);
    SDL2R_DEFINE_ENUM_VALUE(ScancodeEnum, SCANCODE_KP_CLEARENTRY);
    SDL2R_DEFINE_ENUM_VALUE(ScancodeEnum, SCANCODE_KP_BINARY);
    SDL2R_DEFINE_ENUM_VALUE(ScancodeEnum, SCANCODE_KP_OCTAL);
    SDL2R_DEFINE_ENUM_VALUE(ScancodeEnum, SCANCODE_KP_DECIMAL);
    SDL2R_DEFINE_ENUM_VALUE(ScancodeEnum, SCANCODE_KP_HEXADECIMAL);
    SDL2R_DEFINE_ENUM_VALUE(ScancodeEnum, SCANCODE_LCTRL);
    SDL2R_DEFINE_ENUM_VALUE(ScancodeEnum, SCANCODE_LSHIFT);
    SDL2R_DEFINE_ENUM_VALUE(ScancodeEnum, SCANCODE_LALT);
    SDL2R_DEFINE_ENUM_VALUE(ScancodeEnum, SCANCODE_LGUI);
    SDL2R_DEFINE_ENUM_VALUE(ScancodeEnum, SCANCODE_RCTRL);
    SDL2R_DEFINE_ENUM_VALUE(ScancodeEnum, SCANCODE_RSHIFT);
    SDL2R_DEFINE_ENUM_VALUE(ScancodeEnum, SCANCODE_RALT);
    SDL2R_DEFINE_ENUM_VALUE(ScancodeEnum, SCANCODE_RGUI);
    SDL2R_DEFINE_ENUM_VALUE(ScancodeEnum, SCANCODE_MODE);
    SDL2R_DEFINE_ENUM_VALUE(ScancodeEnum, SCANCODE_AUDIONEXT);
    SDL2R_DEFINE_ENUM_VALUE(ScancodeEnum, SCANCODE_AUDIOPREV);
    SDL2R_DEFINE_ENUM_VALUE(ScancodeEnum, SCANCODE_AUDIOSTOP);
    SDL2R_DEFINE_ENUM_VALUE(ScancodeEnum, SCANCODE_AUDIOPLAY);
    SDL2R_DEFINE_ENUM_VALUE(ScancodeEnum, SCANCODE_AUDIOMUTE);
    SDL2R_DEFINE_ENUM_VALUE(ScancodeEnum, SCANCODE_MEDIASELECT);
    SDL2R_DEFINE_ENUM_VALUE(ScancodeEnum, SCANCODE_WWW);
    SDL2R_DEFINE_ENUM_VALUE(ScancodeEnum, SCANCODE_MAIL);
    SDL2R_DEFINE_ENUM_VALUE(ScancodeEnum, SCANCODE_CALCULATOR);
    SDL2R_DEFINE_ENUM_VALUE(ScancodeEnum, SCANCODE_COMPUTER);
    SDL2R_DEFINE_ENUM_VALUE(ScancodeEnum, SCANCODE_AC_SEARCH);
    SDL2R_DEFINE_ENUM_VALUE(ScancodeEnum, SCANCODE_AC_HOME);
    SDL2R_DEFINE_ENUM_VALUE(ScancodeEnum, SCANCODE_AC_BACK);
    SDL2R_DEFINE_ENUM_VALUE(ScancodeEnum, SCANCODE_AC_FORWARD);
    SDL2R_DEFINE_ENUM_VALUE(ScancodeEnum, SCANCODE_AC_STOP);
    SDL2R_DEFINE_ENUM_VALUE(ScancodeEnum, SCANCODE_AC_REFRESH);
    SDL2R_DEFINE_ENUM_VALUE(ScancodeEnum, SCANCODE_AC_BOOKMARKS);
    SDL2R_DEFINE_ENUM_VALUE(ScancodeEnum, SCANCODE_BRIGHTNESSDOWN);
    SDL2R_DEFINE_ENUM_VALUE(ScancodeEnum, SCANCODE_BRIGHTNESSUP);
    SDL2R_DEFINE_ENUM_VALUE(ScancodeEnum, SCANCODE_DISPLAYSWITCH);
    SDL2R_DEFINE_ENUM_VALUE(ScancodeEnum, SCANCODE_KBDILLUMTOGGLE);
    SDL2R_DEFINE_ENUM_VALUE(ScancodeEnum, SCANCODE_KBDILLUMDOWN);
    SDL2R_DEFINE_ENUM_VALUE(ScancodeEnum, SCANCODE_KBDILLUMUP);
    SDL2R_DEFINE_ENUM_VALUE(ScancodeEnum, SCANCODE_EJECT);
    SDL2R_DEFINE_ENUM_VALUE(ScancodeEnum, SCANCODE_SLEEP);
    SDL2R_DEFINE_ENUM_VALUE(ScancodeEnum, SCANCODE_APP1);
    SDL2R_DEFINE_ENUM_VALUE(ScancodeEnum, SCANCODE_APP2);
    SDL2R_DEFINE_ENUM_VALUE(ScancodeEnum, NUM_SCANCODES);

#define SDL2R_DEFINE_ENUM_VALUE_K(t, v) {rb_hash_aset(sdl2r_enum_##t, INT2NUM(SDL##v), rb_str_new(#v, strlen(#v)));rb_define_const(mSDL, #v, INT2NUM(SDL##v));}
    SDL2R_DEFINE_ENUM(KeycodeEnum);
    SDL2R_DEFINE_ENUM_VALUE_K(KeycodeEnum, K_UNKNOWN);
    SDL2R_DEFINE_ENUM_VALUE_K(KeycodeEnum, K_RETURN);
    SDL2R_DEFINE_ENUM_VALUE_K(KeycodeEnum, K_ESCAPE);
    SDL2R_DEFINE_ENUM_VALUE_K(KeycodeEnum, K_BACKSPACE);
    SDL2R_DEFINE_ENUM_VALUE_K(KeycodeEnum, K_TAB);
    SDL2R_DEFINE_ENUM_VALUE_K(KeycodeEnum, K_SPACE);
    SDL2R_DEFINE_ENUM_VALUE_K(KeycodeEnum, K_EXCLAIM);
    SDL2R_DEFINE_ENUM_VALUE_K(KeycodeEnum, K_QUOTEDBL);
    SDL2R_DEFINE_ENUM_VALUE_K(KeycodeEnum, K_HASH);
    SDL2R_DEFINE_ENUM_VALUE_K(KeycodeEnum, K_PERCENT);
    SDL2R_DEFINE_ENUM_VALUE_K(KeycodeEnum, K_DOLLAR);
    SDL2R_DEFINE_ENUM_VALUE_K(KeycodeEnum, K_AMPERSAND);
    SDL2R_DEFINE_ENUM_VALUE_K(KeycodeEnum, K_QUOTE);
    SDL2R_DEFINE_ENUM_VALUE_K(KeycodeEnum, K_LEFTPAREN);
    SDL2R_DEFINE_ENUM_VALUE_K(KeycodeEnum, K_RIGHTPAREN);
    SDL2R_DEFINE_ENUM_VALUE_K(KeycodeEnum, K_ASTERISK);
    SDL2R_DEFINE_ENUM_VALUE_K(KeycodeEnum, K_PLUS);
    SDL2R_DEFINE_ENUM_VALUE_K(KeycodeEnum, K_COMMA);
    SDL2R_DEFINE_ENUM_VALUE_K(KeycodeEnum, K_MINUS);
    SDL2R_DEFINE_ENUM_VALUE_K(KeycodeEnum, K_PERIOD);
    SDL2R_DEFINE_ENUM_VALUE_K(KeycodeEnum, K_SLASH);
    SDL2R_DEFINE_ENUM_VALUE_K(KeycodeEnum, K_0);
    SDL2R_DEFINE_ENUM_VALUE_K(KeycodeEnum, K_1);
    SDL2R_DEFINE_ENUM_VALUE_K(KeycodeEnum, K_2);
    SDL2R_DEFINE_ENUM_VALUE_K(KeycodeEnum, K_3);
    SDL2R_DEFINE_ENUM_VALUE_K(KeycodeEnum, K_4);
    SDL2R_DEFINE_ENUM_VALUE_K(KeycodeEnum, K_5);
    SDL2R_DEFINE_ENUM_VALUE_K(KeycodeEnum, K_6);
    SDL2R_DEFINE_ENUM_VALUE_K(KeycodeEnum, K_7);
    SDL2R_DEFINE_ENUM_VALUE_K(KeycodeEnum, K_8);
    SDL2R_DEFINE_ENUM_VALUE_K(KeycodeEnum, K_9);
    SDL2R_DEFINE_ENUM_VALUE_K(KeycodeEnum, K_COLON);
    SDL2R_DEFINE_ENUM_VALUE_K(KeycodeEnum, K_SEMICOLON);
    SDL2R_DEFINE_ENUM_VALUE_K(KeycodeEnum, K_LESS);
    SDL2R_DEFINE_ENUM_VALUE_K(KeycodeEnum, K_EQUALS);
    SDL2R_DEFINE_ENUM_VALUE_K(KeycodeEnum, K_GREATER);
    SDL2R_DEFINE_ENUM_VALUE_K(KeycodeEnum, K_QUESTION);
    SDL2R_DEFINE_ENUM_VALUE_K(KeycodeEnum, K_AT);
    SDL2R_DEFINE_ENUM_VALUE_K(KeycodeEnum, K_LEFTBRACKET);
    SDL2R_DEFINE_ENUM_VALUE_K(KeycodeEnum, K_BACKSLASH);
    SDL2R_DEFINE_ENUM_VALUE_K(KeycodeEnum, K_RIGHTBRACKET);
    SDL2R_DEFINE_ENUM_VALUE_K(KeycodeEnum, K_CARET);
    SDL2R_DEFINE_ENUM_VALUE_K(KeycodeEnum, K_UNDERSCORE);
    SDL2R_DEFINE_ENUM_VALUE_K(KeycodeEnum, K_BACKQUOTE);
    SDL2R_DEFINE_ENUM_VALUE_K(KeycodeEnum, K_a);
    SDL2R_DEFINE_ENUM_VALUE_K(KeycodeEnum, K_b);
    SDL2R_DEFINE_ENUM_VALUE_K(KeycodeEnum, K_c);
    SDL2R_DEFINE_ENUM_VALUE_K(KeycodeEnum, K_d);
    SDL2R_DEFINE_ENUM_VALUE_K(KeycodeEnum, K_e);
    SDL2R_DEFINE_ENUM_VALUE_K(KeycodeEnum, K_f);
    SDL2R_DEFINE_ENUM_VALUE_K(KeycodeEnum, K_g);
    SDL2R_DEFINE_ENUM_VALUE_K(KeycodeEnum, K_h);
    SDL2R_DEFINE_ENUM_VALUE_K(KeycodeEnum, K_i);
    SDL2R_DEFINE_ENUM_VALUE_K(KeycodeEnum, K_j);
    SDL2R_DEFINE_ENUM_VALUE_K(KeycodeEnum, K_k);
    SDL2R_DEFINE_ENUM_VALUE_K(KeycodeEnum, K_l);
    SDL2R_DEFINE_ENUM_VALUE_K(KeycodeEnum, K_m);
    SDL2R_DEFINE_ENUM_VALUE_K(KeycodeEnum, K_n);
    SDL2R_DEFINE_ENUM_VALUE_K(KeycodeEnum, K_o);
    SDL2R_DEFINE_ENUM_VALUE_K(KeycodeEnum, K_p);
    SDL2R_DEFINE_ENUM_VALUE_K(KeycodeEnum, K_q);
    SDL2R_DEFINE_ENUM_VALUE_K(KeycodeEnum, K_r);
    SDL2R_DEFINE_ENUM_VALUE_K(KeycodeEnum, K_s);
    SDL2R_DEFINE_ENUM_VALUE_K(KeycodeEnum, K_t);
    SDL2R_DEFINE_ENUM_VALUE_K(KeycodeEnum, K_u);
    SDL2R_DEFINE_ENUM_VALUE_K(KeycodeEnum, K_v);
    SDL2R_DEFINE_ENUM_VALUE_K(KeycodeEnum, K_w);
    SDL2R_DEFINE_ENUM_VALUE_K(KeycodeEnum, K_x);
    SDL2R_DEFINE_ENUM_VALUE_K(KeycodeEnum, K_y);
    SDL2R_DEFINE_ENUM_VALUE_K(KeycodeEnum, K_z);
    SDL2R_DEFINE_ENUM_VALUE_K(KeycodeEnum, K_CAPSLOCK);
    SDL2R_DEFINE_ENUM_VALUE_K(KeycodeEnum, K_F1);
    SDL2R_DEFINE_ENUM_VALUE_K(KeycodeEnum, K_F2);
    SDL2R_DEFINE_ENUM_VALUE_K(KeycodeEnum, K_F3);
    SDL2R_DEFINE_ENUM_VALUE_K(KeycodeEnum, K_F4);
    SDL2R_DEFINE_ENUM_VALUE_K(KeycodeEnum, K_F5);
    SDL2R_DEFINE_ENUM_VALUE_K(KeycodeEnum, K_F6);
    SDL2R_DEFINE_ENUM_VALUE_K(KeycodeEnum, K_F7);
    SDL2R_DEFINE_ENUM_VALUE_K(KeycodeEnum, K_F8);
    SDL2R_DEFINE_ENUM_VALUE_K(KeycodeEnum, K_F9);
    SDL2R_DEFINE_ENUM_VALUE_K(KeycodeEnum, K_F10);
    SDL2R_DEFINE_ENUM_VALUE_K(KeycodeEnum, K_F11);
    SDL2R_DEFINE_ENUM_VALUE_K(KeycodeEnum, K_F12);
    SDL2R_DEFINE_ENUM_VALUE_K(KeycodeEnum, K_PRINTSCREEN);
    SDL2R_DEFINE_ENUM_VALUE_K(KeycodeEnum, K_SCROLLLOCK);
    SDL2R_DEFINE_ENUM_VALUE_K(KeycodeEnum, K_PAUSE);
    SDL2R_DEFINE_ENUM_VALUE_K(KeycodeEnum, K_INSERT);
    SDL2R_DEFINE_ENUM_VALUE_K(KeycodeEnum, K_HOME);
    SDL2R_DEFINE_ENUM_VALUE_K(KeycodeEnum, K_PAGEUP);
    SDL2R_DEFINE_ENUM_VALUE_K(KeycodeEnum, K_DELETE);
    SDL2R_DEFINE_ENUM_VALUE_K(KeycodeEnum, K_END);
    SDL2R_DEFINE_ENUM_VALUE_K(KeycodeEnum, K_PAGEDOWN);
    SDL2R_DEFINE_ENUM_VALUE_K(KeycodeEnum, K_RIGHT);
    SDL2R_DEFINE_ENUM_VALUE_K(KeycodeEnum, K_LEFT);
    SDL2R_DEFINE_ENUM_VALUE_K(KeycodeEnum, K_DOWN);
    SDL2R_DEFINE_ENUM_VALUE_K(KeycodeEnum, K_UP);
    SDL2R_DEFINE_ENUM_VALUE_K(KeycodeEnum, K_NUMLOCKCLEAR);
    SDL2R_DEFINE_ENUM_VALUE_K(KeycodeEnum, K_KP_DIVIDE);
    SDL2R_DEFINE_ENUM_VALUE_K(KeycodeEnum, K_KP_MULTIPLY);
    SDL2R_DEFINE_ENUM_VALUE_K(KeycodeEnum, K_KP_MINUS);
    SDL2R_DEFINE_ENUM_VALUE_K(KeycodeEnum, K_KP_PLUS);
    SDL2R_DEFINE_ENUM_VALUE_K(KeycodeEnum, K_KP_ENTER);
    SDL2R_DEFINE_ENUM_VALUE_K(KeycodeEnum, K_KP_1);
    SDL2R_DEFINE_ENUM_VALUE_K(KeycodeEnum, K_KP_2);
    SDL2R_DEFINE_ENUM_VALUE_K(KeycodeEnum, K_KP_3);
    SDL2R_DEFINE_ENUM_VALUE_K(KeycodeEnum, K_KP_4);
    SDL2R_DEFINE_ENUM_VALUE_K(KeycodeEnum, K_KP_5);
    SDL2R_DEFINE_ENUM_VALUE_K(KeycodeEnum, K_KP_6);
    SDL2R_DEFINE_ENUM_VALUE_K(KeycodeEnum, K_KP_7);
    SDL2R_DEFINE_ENUM_VALUE_K(KeycodeEnum, K_KP_8);
    SDL2R_DEFINE_ENUM_VALUE_K(KeycodeEnum, K_KP_9);
    SDL2R_DEFINE_ENUM_VALUE_K(KeycodeEnum, K_KP_0);
    SDL2R_DEFINE_ENUM_VALUE_K(KeycodeEnum, K_KP_PERIOD);
    SDL2R_DEFINE_ENUM_VALUE_K(KeycodeEnum, K_APPLICATION);
    SDL2R_DEFINE_ENUM_VALUE_K(KeycodeEnum, K_POWER);
    SDL2R_DEFINE_ENUM_VALUE_K(KeycodeEnum, K_KP_EQUALS);
    SDL2R_DEFINE_ENUM_VALUE_K(KeycodeEnum, K_F13);
    SDL2R_DEFINE_ENUM_VALUE_K(KeycodeEnum, K_F14);
    SDL2R_DEFINE_ENUM_VALUE_K(KeycodeEnum, K_F15);
    SDL2R_DEFINE_ENUM_VALUE_K(KeycodeEnum, K_F16);
    SDL2R_DEFINE_ENUM_VALUE_K(KeycodeEnum, K_F17);
    SDL2R_DEFINE_ENUM_VALUE_K(KeycodeEnum, K_F18);
    SDL2R_DEFINE_ENUM_VALUE_K(KeycodeEnum, K_F19);
    SDL2R_DEFINE_ENUM_VALUE_K(KeycodeEnum, K_F20);
    SDL2R_DEFINE_ENUM_VALUE_K(KeycodeEnum, K_F21);
    SDL2R_DEFINE_ENUM_VALUE_K(KeycodeEnum, K_F22);
    SDL2R_DEFINE_ENUM_VALUE_K(KeycodeEnum, K_F23);
    SDL2R_DEFINE_ENUM_VALUE_K(KeycodeEnum, K_F24);
    SDL2R_DEFINE_ENUM_VALUE_K(KeycodeEnum, K_EXECUTE);
    SDL2R_DEFINE_ENUM_VALUE_K(KeycodeEnum, K_HELP);
    SDL2R_DEFINE_ENUM_VALUE_K(KeycodeEnum, K_MENU);
    SDL2R_DEFINE_ENUM_VALUE_K(KeycodeEnum, K_SELECT);
    SDL2R_DEFINE_ENUM_VALUE_K(KeycodeEnum, K_STOP);
    SDL2R_DEFINE_ENUM_VALUE_K(KeycodeEnum, K_AGAIN);
    SDL2R_DEFINE_ENUM_VALUE_K(KeycodeEnum, K_UNDO);
    SDL2R_DEFINE_ENUM_VALUE_K(KeycodeEnum, K_CUT);
    SDL2R_DEFINE_ENUM_VALUE_K(KeycodeEnum, K_COPY);
    SDL2R_DEFINE_ENUM_VALUE_K(KeycodeEnum, K_PASTE);
    SDL2R_DEFINE_ENUM_VALUE_K(KeycodeEnum, K_FIND);
    SDL2R_DEFINE_ENUM_VALUE_K(KeycodeEnum, K_MUTE);
    SDL2R_DEFINE_ENUM_VALUE_K(KeycodeEnum, K_VOLUMEUP);
    SDL2R_DEFINE_ENUM_VALUE_K(KeycodeEnum, K_VOLUMEDOWN);
    SDL2R_DEFINE_ENUM_VALUE_K(KeycodeEnum, K_KP_COMMA);
    SDL2R_DEFINE_ENUM_VALUE_K(KeycodeEnum, K_KP_EQUALSAS400);
    SDL2R_DEFINE_ENUM_VALUE_K(KeycodeEnum, K_ALTERASE);
    SDL2R_DEFINE_ENUM_VALUE_K(KeycodeEnum, K_SYSREQ);
    SDL2R_DEFINE_ENUM_VALUE_K(KeycodeEnum, K_CANCEL);
    SDL2R_DEFINE_ENUM_VALUE_K(KeycodeEnum, K_CLEAR);
    SDL2R_DEFINE_ENUM_VALUE_K(KeycodeEnum, K_PRIOR);
    SDL2R_DEFINE_ENUM_VALUE_K(KeycodeEnum, K_RETURN2);
    SDL2R_DEFINE_ENUM_VALUE_K(KeycodeEnum, K_SEPARATOR);
    SDL2R_DEFINE_ENUM_VALUE_K(KeycodeEnum, K_OUT);
    SDL2R_DEFINE_ENUM_VALUE_K(KeycodeEnum, K_OPER);
    SDL2R_DEFINE_ENUM_VALUE_K(KeycodeEnum, K_CLEARAGAIN);
    SDL2R_DEFINE_ENUM_VALUE_K(KeycodeEnum, K_CRSEL);
    SDL2R_DEFINE_ENUM_VALUE_K(KeycodeEnum, K_EXSEL);
    SDL2R_DEFINE_ENUM_VALUE_K(KeycodeEnum, K_KP_00);
    SDL2R_DEFINE_ENUM_VALUE_K(KeycodeEnum, K_KP_000);
    SDL2R_DEFINE_ENUM_VALUE_K(KeycodeEnum, K_THOUSANDSSEPARATOR);
    SDL2R_DEFINE_ENUM_VALUE_K(KeycodeEnum, K_DECIMALSEPARATOR);
    SDL2R_DEFINE_ENUM_VALUE_K(KeycodeEnum, K_CURRENCYUNIT);
    SDL2R_DEFINE_ENUM_VALUE_K(KeycodeEnum, K_CURRENCYSUBUNIT);
    SDL2R_DEFINE_ENUM_VALUE_K(KeycodeEnum, K_KP_LEFTPAREN);
    SDL2R_DEFINE_ENUM_VALUE_K(KeycodeEnum, K_KP_RIGHTPAREN);
    SDL2R_DEFINE_ENUM_VALUE_K(KeycodeEnum, K_KP_LEFTBRACE);
    SDL2R_DEFINE_ENUM_VALUE_K(KeycodeEnum, K_KP_RIGHTBRACE);
    SDL2R_DEFINE_ENUM_VALUE_K(KeycodeEnum, K_KP_TAB);
    SDL2R_DEFINE_ENUM_VALUE_K(KeycodeEnum, K_KP_BACKSPACE);
    SDL2R_DEFINE_ENUM_VALUE_K(KeycodeEnum, K_KP_A);
    SDL2R_DEFINE_ENUM_VALUE_K(KeycodeEnum, K_KP_B);
    SDL2R_DEFINE_ENUM_VALUE_K(KeycodeEnum, K_KP_C);
    SDL2R_DEFINE_ENUM_VALUE_K(KeycodeEnum, K_KP_D);
    SDL2R_DEFINE_ENUM_VALUE_K(KeycodeEnum, K_KP_E);
    SDL2R_DEFINE_ENUM_VALUE_K(KeycodeEnum, K_KP_F);
    SDL2R_DEFINE_ENUM_VALUE_K(KeycodeEnum, K_KP_XOR);
    SDL2R_DEFINE_ENUM_VALUE_K(KeycodeEnum, K_KP_POWER);
    SDL2R_DEFINE_ENUM_VALUE_K(KeycodeEnum, K_KP_PERCENT);
    SDL2R_DEFINE_ENUM_VALUE_K(KeycodeEnum, K_KP_LESS);
    SDL2R_DEFINE_ENUM_VALUE_K(KeycodeEnum, K_KP_GREATER);
    SDL2R_DEFINE_ENUM_VALUE_K(KeycodeEnum, K_KP_AMPERSAND);
    SDL2R_DEFINE_ENUM_VALUE_K(KeycodeEnum, K_KP_DBLAMPERSAND);
    SDL2R_DEFINE_ENUM_VALUE_K(KeycodeEnum, K_KP_VERTICALBAR);
    SDL2R_DEFINE_ENUM_VALUE_K(KeycodeEnum, K_KP_DBLVERTICALBAR);
    SDL2R_DEFINE_ENUM_VALUE_K(KeycodeEnum, K_KP_COLON);
    SDL2R_DEFINE_ENUM_VALUE_K(KeycodeEnum, K_KP_HASH);
    SDL2R_DEFINE_ENUM_VALUE_K(KeycodeEnum, K_KP_SPACE);
    SDL2R_DEFINE_ENUM_VALUE_K(KeycodeEnum, K_KP_AT);
    SDL2R_DEFINE_ENUM_VALUE_K(KeycodeEnum, K_KP_EXCLAM);
    SDL2R_DEFINE_ENUM_VALUE_K(KeycodeEnum, K_KP_MEMSTORE);
    SDL2R_DEFINE_ENUM_VALUE_K(KeycodeEnum, K_KP_MEMRECALL);
    SDL2R_DEFINE_ENUM_VALUE_K(KeycodeEnum, K_KP_MEMCLEAR);
    SDL2R_DEFINE_ENUM_VALUE_K(KeycodeEnum, K_KP_MEMADD);
    SDL2R_DEFINE_ENUM_VALUE_K(KeycodeEnum, K_KP_MEMSUBTRACT);
    SDL2R_DEFINE_ENUM_VALUE_K(KeycodeEnum, K_KP_MEMMULTIPLY);
    SDL2R_DEFINE_ENUM_VALUE_K(KeycodeEnum, K_KP_MEMDIVIDE);
    SDL2R_DEFINE_ENUM_VALUE_K(KeycodeEnum, K_KP_PLUSMINUS);
    SDL2R_DEFINE_ENUM_VALUE_K(KeycodeEnum, K_KP_CLEAR);
    SDL2R_DEFINE_ENUM_VALUE_K(KeycodeEnum, K_KP_CLEARENTRY);
    SDL2R_DEFINE_ENUM_VALUE_K(KeycodeEnum, K_KP_BINARY);
    SDL2R_DEFINE_ENUM_VALUE_K(KeycodeEnum, K_KP_OCTAL);
    SDL2R_DEFINE_ENUM_VALUE_K(KeycodeEnum, K_KP_DECIMAL);
    SDL2R_DEFINE_ENUM_VALUE_K(KeycodeEnum, K_KP_HEXADECIMAL);
    SDL2R_DEFINE_ENUM_VALUE_K(KeycodeEnum, K_LCTRL);
    SDL2R_DEFINE_ENUM_VALUE_K(KeycodeEnum, K_LSHIFT);
    SDL2R_DEFINE_ENUM_VALUE_K(KeycodeEnum, K_LALT);
    SDL2R_DEFINE_ENUM_VALUE_K(KeycodeEnum, K_LGUI);
    SDL2R_DEFINE_ENUM_VALUE_K(KeycodeEnum, K_RCTRL);
    SDL2R_DEFINE_ENUM_VALUE_K(KeycodeEnum, K_RSHIFT);
    SDL2R_DEFINE_ENUM_VALUE_K(KeycodeEnum, K_RALT);
    SDL2R_DEFINE_ENUM_VALUE_K(KeycodeEnum, K_RGUI);
    SDL2R_DEFINE_ENUM_VALUE_K(KeycodeEnum, K_MODE);
    SDL2R_DEFINE_ENUM_VALUE_K(KeycodeEnum, K_AUDIONEXT);
    SDL2R_DEFINE_ENUM_VALUE_K(KeycodeEnum, K_AUDIOPREV);
    SDL2R_DEFINE_ENUM_VALUE_K(KeycodeEnum, K_AUDIOSTOP);
    SDL2R_DEFINE_ENUM_VALUE_K(KeycodeEnum, K_AUDIOPLAY);
    SDL2R_DEFINE_ENUM_VALUE_K(KeycodeEnum, K_AUDIOMUTE);
    SDL2R_DEFINE_ENUM_VALUE_K(KeycodeEnum, K_MEDIASELECT);
    SDL2R_DEFINE_ENUM_VALUE_K(KeycodeEnum, K_WWW);
    SDL2R_DEFINE_ENUM_VALUE_K(KeycodeEnum, K_MAIL);
    SDL2R_DEFINE_ENUM_VALUE_K(KeycodeEnum, K_CALCULATOR);
    SDL2R_DEFINE_ENUM_VALUE_K(KeycodeEnum, K_COMPUTER);
    SDL2R_DEFINE_ENUM_VALUE_K(KeycodeEnum, K_AC_SEARCH);
    SDL2R_DEFINE_ENUM_VALUE_K(KeycodeEnum, K_AC_HOME);
    SDL2R_DEFINE_ENUM_VALUE_K(KeycodeEnum, K_AC_BACK);
    SDL2R_DEFINE_ENUM_VALUE_K(KeycodeEnum, K_AC_FORWARD);
    SDL2R_DEFINE_ENUM_VALUE_K(KeycodeEnum, K_AC_STOP);
    SDL2R_DEFINE_ENUM_VALUE_K(KeycodeEnum, K_AC_REFRESH);
    SDL2R_DEFINE_ENUM_VALUE_K(KeycodeEnum, K_AC_BOOKMARKS);
    SDL2R_DEFINE_ENUM_VALUE_K(KeycodeEnum, K_BRIGHTNESSDOWN);
    SDL2R_DEFINE_ENUM_VALUE_K(KeycodeEnum, K_BRIGHTNESSUP);
    SDL2R_DEFINE_ENUM_VALUE_K(KeycodeEnum, K_DISPLAYSWITCH);
    SDL2R_DEFINE_ENUM_VALUE_K(KeycodeEnum, K_KBDILLUMTOGGLE);
    SDL2R_DEFINE_ENUM_VALUE_K(KeycodeEnum, K_KBDILLUMDOWN);
    SDL2R_DEFINE_ENUM_VALUE_K(KeycodeEnum, K_KBDILLUMUP);
    SDL2R_DEFINE_ENUM_VALUE_K(KeycodeEnum, K_EJECT);
    SDL2R_DEFINE_ENUM_VALUE_K(KeycodeEnum, K_SLEEP);

    SDL2R_DEFINE_ENUM(KeymodEnum);
    SDL2R_DEFINE_ENUM_VALUE_N(KeymodEnum, KMOD_NONE);
    SDL2R_DEFINE_ENUM_VALUE_N(KeymodEnum, KMOD_LSHIFT);
    SDL2R_DEFINE_ENUM_VALUE_N(KeymodEnum, KMOD_RSHIFT);
    SDL2R_DEFINE_ENUM_VALUE_N(KeymodEnum, KMOD_LCTRL);
    SDL2R_DEFINE_ENUM_VALUE_N(KeymodEnum, KMOD_RCTRL);
    SDL2R_DEFINE_ENUM_VALUE_N(KeymodEnum, KMOD_LALT);
    SDL2R_DEFINE_ENUM_VALUE_N(KeymodEnum, KMOD_RALT);
    SDL2R_DEFINE_ENUM_VALUE_N(KeymodEnum, KMOD_LGUI);
    SDL2R_DEFINE_ENUM_VALUE_N(KeymodEnum, KMOD_RGUI);
    SDL2R_DEFINE_ENUM_VALUE_N(KeymodEnum, KMOD_NUM);
    SDL2R_DEFINE_ENUM_VALUE_N(KeymodEnum, KMOD_CAPS);
    SDL2R_DEFINE_ENUM_VALUE_N(KeymodEnum, KMOD_MODE);
    SDL2R_DEFINE_ENUM_VALUE_N(KeymodEnum, KMOD_RESERVED);
    SDL2R_DEFINE_ENUM_VALUE_N(KeymodEnum, KMOD_CTRL);
    SDL2R_DEFINE_ENUM_VALUE_N(KeymodEnum, KMOD_SHIFT);
    SDL2R_DEFINE_ENUM_VALUE_N(KeymodEnum, KMOD_ALT);
    SDL2R_DEFINE_ENUM_VALUE_N(KeymodEnum, KMOD_GUI);
}
